baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Timeless Halts"
theme = "PaperMod"

[taxonomies]
category = "categories"
tag = "tags"

[params]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
defaultTheme = "light"

[params.homeInfoParams]
Title = "Welcome to Timeless Halts"
Content = "Personal stories, railway memories, and thoughtful journeys — all coming to a gentle halt here."